Enter the preorder traversal of the BST: Enter value of lower: Enter value of upper: BST before trimming values between 1 and 4:

              8
             / \
            /   \
           /     \
          /       \
         /         \
        /           \
       /             \
      4              12
     / \             / \
    /   \           /   \
   /     \         /     \
  2       6       10     14
 / \     / \     / \     / \
1   3   5   7   9  11   /   \
                       13   15

BST after trimming values between 1 and 4:
=== ignored by test >>>

      8
     / \
    /   \
   /     \
  6      12
 / \     / \
5   7   /   \
       /     \
      10     14
     / \     / \
    9  11   /   \
           13   15

<<< ignored by test ===

Inorder traversal of the BST: 5 6 7 8 9 10 11 12 13 14 15 
